CompileError/CompileError/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using CompileError.Model.Model;
using CompilerError.Models;

using AutoMapper;
using CompileError.Manager.Manager;

namespace CompilerError.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        CategoryManager _categoryManager = new CategoryManager();

        [HttpGet]
        public ActionResult Add()
        {
            CategoryViewModel categoryViewModel = new CategoryViewModel();
            categoryViewModel.Categories = _categoryManager.GetAll();
            return View(categoryViewModel);
        }
        [HttpPost]
        public ActionResult Add(CategoryViewModel categoryViewModel)
        {

            string message = "";
            if (ModelState.IsValid)
            {

                Category category = Mapper.Map<Category>(categoryViewModel);

                if (_categoryManager.Add(category))
                {
                    message = "save";

                }
                else
                {
                    message = "not saved";
                }

            }

            categoryViewModel.Categories = _categoryManager.GetAll();
            ViewBag.Message = message;
            return View(categoryViewModel);
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            CategoryViewModel categoryViewModel = Mapper.Map<CategoryViewModel>(_categoryManager.Search(id));
            categoryViewModel.Categories = _categoryManager.GetAll();
            return View(categoryViewModel);

        }
        [HttpPost]
        public ActionResult Update(CategoryViewModel categoryViewModel)
        {
            Category category = Mapper.Map<Category>(categoryViewModel);
            _categoryManager.Update(category);
            categoryViewModel.Categories = _categoryManager.GetAll();
            return View(categoryViewModel);
            // return RedirectToAction("Add");

        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            _categoryManager.Delete(id);
            return RedirectToAction("Add");

        }

        [HttpGet]
        public ActionResult Search()
        {
            CategoryViewModel categoryViewModel = new CategoryViewModel();
            categoryViewModel.Categories = _categoryManager.GetAll();
            return View(categoryViewModel);
        }

        [HttpPost]
        public ActionResult Search(CategoryViewModel categoryViewModel)
        {
            List<Category> categories = _categoryManager.GetAll();

            if (categoryViewModel.Code != null)
            {
                categories = categories.Where(c => c.Code.Contains(categoryViewModel.Code)).ToList();
            }
            categoryViewModel.Categories = categories;
            return View(categoryViewModel);
        }
    }
}

CompileError/CompileError/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CompileError.Model.Model;
using CompileError.Manager.Manager;
using CompileError.Models;

namespace CompileError.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductManager _productManager = new ProductManager();
        private readonly CategoryManager _categoryManager = new CategoryManager();

        [HttpGet]
        public ActionResult AddProduct()
        {
            ProductModelView productModelView = new ProductModelView()
            {
                Products = _productManager.GetAll(),
                CategorySelectListItems = _categoryManager.GetAll()
                    .Select(c=>new SelectListItem()
                    {
                        Value = c.Id.ToString(),
                        Text = c.Name
                    }).ToList()
            };

            

            return View(productModelView);
        }

        [HttpPost]
        public ActionResult AddProduct(ProductModelView productModelView)
        {
            Product product = Mapper.Map<Product>(productModelView);

            if(ModelState.IsValid)
            {
                ViewBag.Message = _productManager.Add(product) ? "Saved" : "Not Saved";
            }
            else
            {
                ViewBag.Message = "Model State Error";
            }

            productModelView.CategorySelectListItems = _categoryManager.GetAll()
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList();

            productModelView.Products = _productManager.GetAll();
            return View(productModelView);
        }

        [HttpGet]
        public ActionResult SearchProduct()
        {
            ProductModelView productModelView = new ProductModelView()
            {
                Products = _productManager.GetAll(),
                CategorySelectListItems = _categoryManager.GetAll()
                    .Select(c=>new SelectListItem()
                    {
                        Value = c.Id.ToString(),
                        Text = c.Name
                            
                    }).ToList()
            };

            return View(productModelView);
        }

        [HttpPost]
        public ActionResult SearchProduct(ProductModelView productModelView)
        {


            var products = _productManager.GetAll();

            if (!string.IsNullOrEmpty(productModelView.Code))
            {
                products = products.Where(p =>
                    p.Code.ToLower().Contains(productModelView.Code.ToLower())).ToList();
            }

            if (!string.IsNullOrEmpty(productModelView.Name))
            {
                products = products.Where(p =>
                    p.Name.ToLower().Contains(productModelView.Name.ToLower())).ToList();
            }

            if (productModelView.CategoryId != 0)
            {
                products = products.Where(p => p.CategoryId == productModelView.CategoryId).ToList();
            }

            if (!string.IsNullOrEmpty(productModelView.Description))
            {
                products = products.Where(p =>
                    p.Description.ToLower().Contains(productModelView.Description.ToLower())).ToList();
            }

            if (!string.IsNullOrEmpty(productModelView.ReorderLevel.ToString()))
            {
                products = products.Where(p =>
                    p.ReorderLevel.ToString().Contains(productModelView.ReorderLevel.ToString())).ToList();
            }

            productModelView.Products = products;
            productModelView.CategorySelectListItems = _categoryManager.GetAll()
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList();
            return View(productModelView);
        }

        [HttpGet]
        public ActionResult EditProduct(int Id)
        {
            Product product = _productManager.GetById(Id);

            ProductModelView productModelView =  Mapper.Map<ProductModelView>(product);

            productModelView.CategorySelectListItems = _categoryManager.GetAll()
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList();
            productModelView.Products = _productManager.GetAll();

            return View(productModelView);
        }

        [HttpPost]
        public ActionResult EditProduct(ProductModelView productModelView)
        {
            Product product = Mapper.Map<Product>(productModelView);

            if (ModelState.IsValid)
            {
                _productManager.Update(product);
            }

            productModelView.Products = _productManager.GetAll();
            productModelView.CategorySelectListItems = _categoryManager.GetAll()
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList();

            return View(productModelView);
        }


    }
}

CompileError/CompileError/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CompileError.Manager.Manager;
using CompileError.Model.Model;
using CompileError.Models;
using AutoMapper;

namespace CompileError.Controllers
{
    public class PurchaseController : Controller
    {
        private readonly CategoryManager _categoryManager = new CategoryManager();
        private readonly ProductManager _productManager = new ProductManager();
        private readonly SupplierManager _supplierManager = new SupplierManager();
        private readonly PurchaseManager _purchaseManager = new PurchaseManager();
        private readonly PurchasedProductManager _purchasedProductManager = new PurchasedProductManager();

        [HttpGet]
        public ActionResult Add()
        {
            PurchaseModelView purchaseModelView = new PurchaseModelView();
            FillComboBox(purchaseModelView);

            return View(purchaseModelView);
        }

        [HttpPost]
        public ActionResult Add(PurchaseModelView purchaseModelView)
        {
            FillComboBox(purchaseModelView);
            return View(purchaseModelView);
        }

        private void FillComboBox(PurchaseModelView purchaseModelView)
        {
            purchaseModelView.CategorySelectListItems = _categoryManager.GetAll()
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList();
            purchaseModelView.SupplierSelectListItems = _supplierManager.GetAll()
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                }).ToList();
            purchaseModelView.ProductSelectListItems = new List<SelectListItem>();
        }

        public JsonResult GetProductJsonResult(int categoryId)
        {
            List<Product> products = _productManager.GetAll()
                .Where(c => c.CategoryId == categoryId).ToList();

            var productIdValue = products.Select(c => new {c.Id, c.Name});

            return Json(productIdValue, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProductInfoJsonResult(int productId)
        {
            PurchaseModelView purchaseModelView = new PurchaseModelView
            {
                ProductCode = _productManager.GetById(productId).Code
            };

            purchaseModelView.PurchasedProducts = _purchasedProductManager.GetAll()
                .Where(c => c.ProductId == productId).ToList();

            if (purchaseModelView.PurchasedProducts.Count!=0)
            {
                var lId = 0;
                foreach (var purchasedProduct in purchaseModelView.PurchasedProducts)
                {
                    if (purchasedProduct.Id > lId)
                    {
                        purchaseModelView.PreviousMrp = purchasedProduct.Mrp;
                        purchaseModelView.PreviousUnitPrice = purchasedProduct.UnitPrice;
                    }
                }
            }

            return Json(purchaseModelView);
        }

        public void AddToPurchaseCart(PurchaseModelView purchaseModelView)
        {

            PurchasedProduct purchasedProduct = Mapper.Map<PurchasedProduct>(purchaseModelView);


            purchaseModelView.PurchasedProducts.Add(purchasedProduct);
        }

        public string TestF()
        {
            return "abc";
        }

    }
}

CompileError/CompileError/Views/Shared/_KLayout.cshtml
@using System.Web.Mvc.Html
@using CompileError.Model.Model

<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ProductForm</title>

    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />

    <style>

        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        .dropdown:hover {
            background: #fc6b03;
        }

        .dropdown:hover .dropdown-menu {
            display: block;
            margin-top: 0px;
        }

        .dropdown:hover .dropdown-menu a:hover {
            color: rgb(33, 209, 57);
        }

        .jumbotron {
            background-color: rgb(193, 197, 182);
        }

        .panel-footer {
            background-color: rgb(24, 21, 9);
            color: #fff;
            border-radius: 0;
            margin-top: 220px;
        }

        @*........For table.......*@

        table {
            width: 100%;
            padding: 30px 0px;
            box-sizing: border-box;
            margin: auto;
        }

        tr{
            padding:10px;
            text-align: left;
        }

        tr:nth-child(even) {
            background-color: #ddd;
        }

        @RenderSection("MyCSS", false)


    </style>

</head>

<body>

    @*Main Header *@

    @*Main Navbar *@
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">
                    <p><span class="text-primary"><strong>SBM</strong></span><span class="text-danger">System</span></p>
                </a>
            </div>

            <ul class=" nav navbar-nav">



                <li class="dropdown">
                    <a href="#">Category</a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="@Url.Action("Add", "Category")"> Add</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Search", "Category")" class="elements"><span>Add</span></a>
                        </li>
                        <li><a href="#">Edit</a></li>
                        <li><a href="#">Remove</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#">Product</a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="@Url.Action("AddProduct", "Product")"> Add</a>
                        </li>
                        <li><a href="#">Search</a></li>
                        <li><a href="#">Edit</a></li>
                        <li><a href="#">Remove</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#">Customer</a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Add</a></li>
                        <li><a href="#">Search</a></li>
                        <li><a href="#">Edit</a></li>
                        <li><a href="#">Remove</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#">Supplier</a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Add</a></li>
                        <li><a href="#">Search</a></li>
                        <li><a href="#">Edit</a></li>
                        <li><a href="#">Remove</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#">Sales</a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Add</a></li>
                        <li><a href="#">Search</a></li>
                        <li><a href="#">Edit</a></li>
                        <li><a href="#">Remove</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#">Purchase</a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="@Url.Action("Add", "Purchase")"> Add</a>
                        </li>
                        <li><a href="#">Search</a></li>
                        <li><a href="#">Edit</a></li>
                        <li><a href="#">Remove</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#">Stock</a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Add</a></li>
                        <li><a href="#">Search</a></li>
                        <li><a href="#">Edit</a></li>
                        <li><a href="#">Remove</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#">Report</a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Add</a></li>
                        <li><a href="#">Search</a></li>
                        <li><a href="#">Edit</a></li>
                        <li><a href="#">Remove</a></li>
                    </ul>
                </li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">About us</a></li>
            </ul>

        </div>
    </nav>
    
    @*Jumbotron *@
    <div class="jumbotron text-center">
        <h1>Welcome<br>To<br><span class="text-primary"><strong>SBM</strong></span><span class="text-danger">System</span>
        </h1>
    </div>
    

<section id="main">
    <div class="container">
        <div class="row">
                
            <!-- Main area -->
            <div class="col-md-9">

                <!-- Render goes here -->
                @*Main Section *@
                @RenderBody()

            </div>

            <!-- Side bar -->
            <div class="col-md-3">
                <div class="list-group">
                    <a href="#" class="list-group-item active">Cras justo odio</a>
                    <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
                    <a href="#" class="list-group-item">Morbi leo risus</a>
                    <a href="#" class="list-group-item">Porta ac consectetur ac</a>
                    <a href="#" class="list-group-item">Vestibulum at eros</a>
                </div>
            </div>

        </div>
    </div>
</section>


<div class="panel-footer">
    <p class="text-center">Copyright &copy; 2019 CompileError</p>
</div>
    
    @* ......Script........ *@
<div>
    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("MyScript", false)
</div>
</body>
</html>